/**
 * Public identifiers.
 *
 * Every id the app puts in a URL, an export or in front of a person is a plain
 * 16-digit number generated by `new_public_id()` (migration 00034). The uuid
 * primary keys still exist and still do all the referential work; they simply
 * never leave the database. See the migration header for why the two cannot be
 * the same column, and why the generated range stops below 2^53 so a public id
 * survives JSON as an exact integer.
 *
 * Values are handled as strings here regardless. The digits are what goes in a
 * URL and what a person reads back to you; converting to a number and back
 * gains nothing and risks reintroducing the precision question at the one place
 * it would be hardest to notice.
 */

/** Exactly sixteen digits, no sign, no separators. */
const PUBLIC_ID_PATTERN = /^\d{16}$/

export function isPublicId(value: unknown): value is string {
  return typeof value === 'string' && PUBLIC_ID_PATTERN.test(value)
}

/**
 * Narrow a route parameter to a public id.
 *
 * Returns null rather than throwing so the caller can answer with a 404, which
 * is what a malformed id in a URL deserves: it is indistinguishable from a
 * deleted row, and distinguishing them would confirm which ids exist.
 */
export function parsePublicId(value: string | undefined | null): string | null {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return PUBLIC_ID_PATTERN.test(trimmed) ? trimmed : null
}

/**
 * A public id as it comes back from the database, rendered for a URL.
 *
 * The generated types say `number` because that is the column type; the value
 * is within the safe range by construction, so this is a formatting step rather
 * than a conversion that could lose anything.
 */
export function publicIdToString(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return ''
  return typeof value === 'number' ? String(Math.trunc(value)) : String(value)
}
